update build-osx

diff --git a/contrib/build-osx/make_osx b/contrib/build-osx/make_osx
--- a/contrib/build-osx/make_osx
+++ b/contrib/build-osx/make_osx
@@ -7,8 +7,8 @@ test -n "$build_dir" -a -d "$build_dir" || exit
 cd $build_dir/../..
 
 export PYTHONHASHSEED=22
-PYTHON_VERSION=3.6.2
-VERSION=`git describe --tags`
+PYTHON_VERSION=3.6.4
+VERSION=`git describe --tags --dirty --always`
 STAGING_DIR="dist"
 VOL_NAME="Qtum Electrum"
 TEMP_DMG_NAME="/tmp/qtum-electrum.dmg"
@@ -19,6 +19,11 @@ LIBSECP_VERSION=b408c6a8b287003d1ade5709e6f7bc3c7f1d5be7
 rm -rf ${STAGING_DIR} ${TEMP_DMG_NAME}
 
 which brew > /dev/null 2>&1 || fail "Please install brew from https://brew.sh/ to continue"
+
+info "Installing zlib and sqlite"
+brew install zlib sqlite
+export LDFLAGS="-L/usr/local/opt/zlib/lib -L/usr/local/opt/sqlite/lib"
+export CPPFLAGS="-I/usr/local/opt/zlib/include -I/usr/local/opt/sqlite/include"
 
 info "Installing Python $PYTHON_VERSION"
 export PATH="~/.pyenv/bin:~/.pyenv/shims:~/Library/Python/3.6/bin:$PATH"
@@ -45,6 +50,8 @@ if [ ! -e contrib/build-osx/libusb-1.0.dylib ] ; then
     tar xz --directory /tmp/
     cp /tmp/libusb/1.0.22/lib/libusb-1.0.dylib contrib/build-osx
 fi
+echo "82c368dfd4da017ceb32b12ca885576f325503428a4966cc09302cbd62702493  contrib/build-osx/libusb-1.0.dylib" | \
+    shasum -a 256 -c || fail "libusb checksum mismatched"
 
 info "Building libsecp256k1"
 brew install autoconf automake libtool
@@ -66,7 +73,7 @@ fail "Could not install requirements"
 
 
 info "Building $PACKAGE..."
-python3 setup.py install --user > /dev/null || fail "Could not build $PACKAGE"
+python3 -m pip install --user > /dev/null || fail "Could not build $PACKAGE"
 
 
 info "Faking timestamps..."
